# Generated by Django 4.2.4 on 2023-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.CharField(max_length=255)),
                ('ticket_date', models.DateField()),
                ('username', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
