# Generated by Django 4.2.4 on 2023-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ticket", "0003_ticket_delete_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="image",
            field=models.ImageField(default="", upload_to="image/"),
        ),
    ]
